name: Build and Test Latest.NET9 Features

on:
  push:
    branches:
      - main  # Run when code is pushed to main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the build agent
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --configuration Release

      - name: Run Tests with Code Coverage
        run: dotnet test --configuration Release --collect "Code Coverage"

      - name: Upload Code Coverage Results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: '**/coverage.cobertura.xml'

      - name: Publish Application
        run: dotnet publish -c Release -o publish/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: latest-net9-build
          path: publish/
